# Generated by Django 5.2.6 on 2025-09-16 12:42

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='before_text',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.CreateModel(
            name='ProjectBeforeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/before/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='before_images', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
