# Generated by Django 5.2.6 on 2025-09-14 13:06

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', ckeditor.fields.RichTextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='site/')),
            ],
            options={
                'verbose_name': 'Bureau',
                'verbose_name_plural': 'Bureau',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('body', ckeditor.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Homepage (Accueil)',
                'verbose_name_plural': 'Homepage (Accueil)',
            },
        ),
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section1_title', models.CharField(blank=True, max_length=200)),
                ('section1_body', ckeditor.fields.RichTextField(blank=True)),
                ('section2_title', models.CharField(blank=True, max_length=200)),
                ('section2_body', ckeditor.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Prestations',
                'verbose_name_plural': 'Prestations',
            },
        ),
        migrations.CreateModel(
            name='HomePageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='site/home/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sitecontent.homepage')),
            ],
            options={
                'verbose_name': 'Homepage image',
                'verbose_name_plural': 'Homepage images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
